# Generated by Django 4.1.4 on 2022-12-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.DecimalField(decimal_places=0, max_digits=3)),
                ("phone_number", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("comment", models.TextField(max_length=50)),
                ("image", models.ImageField(blank=True, upload_to="crud_app/static/")),
                ("national_id", models.CharField(max_length=50)),
            ],
        ),
    ]
